
export const CATS = {
  kpz:  { label: '★ Kampfpanzer',           short: 'KPz',       color: '#6b2200', light: '#f87171', sub: 'Handout 100', superCat: 'russia', recoType: 'Tanks' },
  spz:  { label: '⚙ Schützenpanzer',        short: 'SPz',       color: '#1e5f3e', light: '#4ade80', sub: 'Handout 200', superCat: 'russia', recoType: 'Infantry-Fighting-Vehicles' },
  tpz:  { label: '▣ Transportpanzer',       short: 'TPz',       color: '#5e2a6e', light: '#c084fc', sub: 'Handout 300', superCat: 'russia', recoType: 'APCs' },
  aufkl:{ label: '◉ Aufklärungsfahrzeuge',  short: 'AufklFz',   color: '#3d4200', light: '#b8cc40', sub: 'Handout 400', superCat: 'russia', recoType: 'Reconnaissance' },
  art:  { label: '⦿ Artillerie & Mörser',  short: 'Art/Mörser',color: '#1a2a4a', light: '#60a0f0', sub: 'Handout 500', superCat: 'russia', recoType: 'Artillery' },
  mlrs: { label: '⟁ Raketenwerfer',         short: 'MLRS',      color: '#4a1a00', light: '#fb923c', sub: 'Handout 600', superCat: 'russia', recoType: 'MLRS' },
}

export const SUPER_CATS = {
  russia: { label: 'Russland / GUS', emoji: '🇷🇺', nations: ['Russland', 'Ukraine'] },
  nato:   { label: 'NATO',           emoji: '🇩🇪', nations: [] },
}

// images: array of direct SmugMug/recomonkey CDN URLs — populated in Phase 2
export const DB = {

kpz: [
  { id:100, nr:100, name:'T-54',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Halbkugeliger runder Turm – älteste sowjetische Nachkriegsgeneration','Keine Außenpanzerung – schlichte Turmform ohne ERA-Blöcke'],
    s:'RUNDER KUGELTURM – ÄLTESTE GENERATION' },
  { id:101, nr:101, name:'T-55',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Wie T-54 + ABC-Schutzventilator hinten rechts auf der Wanne','Kein Kommandantenlupf – flacher Drehkranz auf dem Turm'],
    s:'WIE T-54 + ABC-VENTILATOR HINTEN RECHTS' },
  { id:102, nr:102, name:'T-62',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Ovaler/elliptischer Turm + langes 115mm-Glattrohr (erster Glattrohr-MBT)','Hülsenauswurfschacht rechts außen am Turm sichtbar'],
    s:'OVALER TURM + 115MM GLATTROHR + HÜLSENAUSWURF RECHTS' },
  { id:103, nr:103, name:'T-64A',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['6 kleine eng beieinanderliegende Laufrollen – kein großer Zwischenraum','Kleiner runder Turm + Gummischürzen an der Wanne'],
    s:'6 KLEINE DICHTE LAUFROLLEN + GUMMISCHÜRZEN' },
  { id:104, nr:104, name:'T-72',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Großer gegossener Pilzturm + 6 Laufrollen','Deutlicher Zwischenraum zwischen 1. und 2. Laufrolle (typisch T-72)'],
    s:'GROSSER PILZTURM + 6 LAUFROLLEN' },
  { id:105, nr:105, name:'T-72A',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Wie T-72 + Sandguss-Zusatzpanzerung auf Turmfront + IR-Scheinwerfer links am Turm','Gummischürzen + Zusatzpanzerung seitlich an der Wanne'],
    s:'T-72 + SANDGUSS TURMFRONT + IR-SCHEINWERFER LINKS' },
  { id:106, nr:106, name:'T-72B',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['NATO: OLCHA / Super Dolly Parton – Kontakt-1 ERA-Blöcke auf Turm und Wanne','Gewölbte Panzerungseinlagen beidseitig der Turmfront (Super Dolly Parton)'],
    s:'ERA KONTAKT-1 + SUPER DOLLY PARTON TURMFRONT' },
  { id:107, nr:107, name:'T-72B3',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Sosna-U Wärmebildoptik (Vierer-Block rechts am Turm) + modernisierte ERA','Neue Seitenschürzen + Sosna-U Optikanlage deutlich erkennbar'],
    s:'SOSNA-U OPTIK (4-BLOCK) + ERA MODERNISIERT' },
  { id:108, nr:108, name:'T-72B3M',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Relikt-ERA (deutlich größere Blöcke als Kontakt-5) auf Turm und Wanne','Verbesserte Seitenverkleidung + Sosna-U 2 Optik'],
    s:'RELIKT-ERA GROSSE BLÖCKE + VERBESSERTE SCHÜRZEN' },
  { id:109, nr:109, name:'T-72BM',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['NATO: SMT M1990 – Kontakt-5 ERA + vollständige Seitenschürzen','Kontakt-5 Blöcke auf dem Wannendach + geändertes Turmheck'],
    s:'KONTAKT-5 ERA + VOLLSTÄNDIGE SEITENSCHÜRZEN' },
  { id:110, nr:110, name:'T-80B',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Gasturbinen-Antrieb + 6 kleinere Laufrollen (wie T-64, nicht wie T-72)','Breiterer Turm als T-64 + Scheinwerfer links am Turm'],
    s:'GASTURBINE + 6 KLEINE LAUFROLLEN WIE T-64' },
  { id:111, nr:111, name:'T-80U',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kontakt-5 ERA auf T-80-Rumpf + Wärmebildgerät rechts am Turm','Modernisierter breiterer Turm gegenüber T-80B'],
    s:'KONTAKT-5 AUF T-80-RUMPF + WBG RECHTS' },
  { id:112, nr:112, name:'T-80UD',   flag:'🇺🇦', nation:'Ukraine', images:[],
    m:['Ukrainische Variante: Dieselmotor statt Gasturbine + geänderter Auspuff','Ukrainische Morozov-Konstruktion – kein Turbinenlärm'],
    s:'UKRAINE + DIESEL STATT GASTURBINE' },
  { id:113, nr:113, name:'T-80BVM',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['NATO: BEREZA – Relikt-ERA + neue Sosna-U-Optik auf T-80B-Rumpf','Modernisierter T-80B: neue Schutzausstattung, gleiches Fahrgestell'],
    s:'RELIKT-ERA + SOSNA-U AUF T-80B-RUMPF' },
  { id:115, nr:115, name:'T-90',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Shtora-1 IR-Störsystem: zwei charakteristische rote „Augen" vorne am Turm','Kontakt-5 ERA + gegossener Turm ähnlich T-72B'],
    s:'ROTE SHTORA-AUGEN AM TURM (IR-STÖRUNG)' },
  { id:116, nr:116, name:'T-90A',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['NATO: WLADIMIR – geschweißter Turm (statt gegossen) + Shtora-1-Augen sichtbar','Neue Turmform + überarbeitete Wannenpanzerung + Wärmebildgerät'],
    s:'GESCHWEISSTER TURM + SHTORA ROTE AUGEN' },
  { id:117, nr:117, name:'T-90M',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Neuer eckiger geschweißter Turm (Proryv-3) + Relikt-ERA auf Turm und Wanne','Panoramasicht-Kuppel für Kommandant + neue Hauptoptik'],
    s:'NEUER ECKIGER TURM + RELIKT-ERA + PANORAMASICHT' },
],

spz: [
  { id:200, nr:200, name:'BMD-1',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Schiffsform (geschwungene Wannenfront) + kleines Schwallbrett + Waschbrett vor MKF','5 Laufrollen + Hydrojets unter Abgasschlitzen am Heck + vertiefender Einstieg'],
    s:'SCHIFFSFORM + 5 LAUFROLLEN + HYDROJETS HECK' },
  { id:201, nr:201, name:'BMD-2',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Lange schmale Kanone + Zusatzblende rechts neben Kanone','Scheinwerfer rechts oben am Turm + Periskop seitlich links'],
    s:'LANGE SCHMALE KANONE + ZUSATZBLENDE RECHTS' },
  { id:202, nr:202, name:'BMD-3',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kantiger/gerader Front + aufgesetzte MG-Luken + Halterung für Fallschirmpakete links','Hydrojets mit Lamellenklappen am Heck + abgeschrägte Oberkante bis 3. Laufrolle'],
    s:'FALLSCHIRM-HALTERUNG LINKS + HYDROJETS MIT LAMELLEN' },
  { id:203, nr:203, name:'BMD-4',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Doppelkanone: 30mm + 100mm + MG in kantig geschweißtem Turm mit schräger Front','Keine GMW-Luke in der Wannenfront (nur noch MG-Luke)'],
    s:'DOPPELKANONE 30MM+100MM + KEINE GMW-LUKE' },
  { id:204, nr:204, name:'BMD-4M',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kein Entenschnabel mehr + 2 kleine MG-Luken + kleines Schwallbrett vorne','Turm mit 2 Optiken + geteilter Abgasschacht auf Höhe letzter Laufrolle'],
    s:'KEIN ENTENSCHNABEL + 2 OPTIKEN IM TURM' },
  { id:205, nr:205, name:'BMP-1',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Großes Schwallbrett + Scheinwerfer mit Bügel vorne + waffelförmige Kettenblenden','Ein-Mann-Turm (eine Optik, Scheinwerfer rechts) + 4 Schützenluken rechts'],
    s:'GROSSES SCHWALLBRETT + EIN-MANN-TURM' },
  { id:206, nr:206, name:'BMP-1AM',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['BTR-Scheitellafette (kein klassischer Turm) auf BMP-1-Wanne + Schutzkragen vorne','Frontpanzerung des Turmersatzes 3-geteilt + eckiges MG rechts'],
    s:'BTR-SCHEITELLAFETTE AUF BMP-1-WANNE' },
  { id:207, nr:207, name:'BMP-2',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['2-Mann-Turm + breite Kettenblenden + 2 Dämpfer vorne rechts','3 Winkelspiegel + 3 Schießluken links + nur 2 Luken hinter Turm'],
    s:'2-MANN-TURM + BREITE KETTENBLENDEN' },
  { id:208, nr:208, name:'BMP-2M',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['NATO: BEREZHOK – AGS-30 Granatmaschinenwaffe mittig auf dem Turm','Panzerabwehrraketen links und rechts am Turm + große Optiktonne'],
    s:'AGS-30 OBEN + AT-RAKETEN LINKS/RECHTS AM TURM' },
  { id:209, nr:209, name:'BMP-3',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Zwillingskanone (100mm + 30mm BMK) vorderes Turmbereich + Laserbeam oben auf Kanone','6 Laufrollen + Hydrojet-Antrieb am Heck + Blenden-MG mit Schutzbügel vorne'],
    s:'ZWILLINGSKANONE + 6 LAUFROLLEN + HYDROJET HECK' },
  { id:210, nr:210, name:'BMP-3M',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['WBG (Wärmebildgerät) links hoch am Turm + Laser rechts neben der BMK (nicht drauf)','Ansonsten wie BMP-3 – kein Laserbeam auf der Kanone selbst'],
    s:'WBG LINKS HOCH AM TURM + LASER RECHTS NEBEN BMK' },
  { id:211, nr:211, name:'BMP-K17',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['NATO: VPK-7829 BUMERANG – 4 AT-Raketen am Turm + 30mm BMK + Datenlink-Antenne','Hydrojet-Turbine am Heck + T-förmige Aufstiegshilfe + moderne eckige Scheinwerfer'],
    s:'4 AT-RAKETEN + DATENLINK-ANTENNE + HYDROJET' },
  { id:212, nr:212, name:'BMP-1M',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['NATO: SHKVAL – modernisierter BMP-1 mit neuem Turmsystem','Handout-Merkmale eintragen (Seite 14)'],
    s:'SHKVAL – HANDOUT AUSSTEHEND' },
],

tpz: [
  { id:300, nr:300, name:'GAZ-233036 TIGR',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Flache Motorhaube (kein Buckel) – Unterschied zu TIGR-M','Nur eine Tür pro Seite'],
    s:'FLACHE HAUBE + NUR 1 TÜR/SEITE' },
  { id:301, nr:301, name:'AMN 233114 TIGR-M',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Motorhaube mit charakteristischem Buckel (Gegenteil zu TIGR)','ABC-Schutzfilter am Heck sichtbar'],
    s:'BUCKELHAUBE + ABC-FILTER HECK' },
  { id:302, nr:302, name:'TYPHOON-K 4x4',      flag:'🇷🇺', nation:'Russland', images:[],
    m:['Haube überlappt Kühlergrill + Seilwinde unter Kühler + 2 Kupplungsmäuler','2 Türen pro Seite (vorderes Fenster größer) + kantig großer Radkasten hinten'],
    s:'HAUBE ÜBERLAPPT KÜHLER + SEILWINDE + 2 KUPPLUNGSMÄULER' },
  { id:303, nr:303, name:'TYPHOON-K 6x6',      flag:'🇷🇺', nation:'Russland', images:[],
    m:['Dreieck nach unten zeigendes Element an der Front + flache Schnauze','6 Räder + 2 Fenster für Kampfraum + 2 Belüftungsgitter links'],
    s:'DREIECK-FRONT NACH UNTEN + FLACHE SCHNAUZE + 6 RÄDER' },
  { id:304, nr:304, name:'TYPHOON-VDV 4x4',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['4 Scheibenwischer von oben (einzigartiges Merkmal!)','Seil-Steighilfe rechts + Kraftstofftank links + optionaler Turm'],
    s:'4 SCHEIBENWISCHER VON OBEN' },
  { id:305, nr:305, name:'TYPHOON-U 6x6',      flag:'🇷🇺', nation:'Russland', images:[],
    m:['LKW-Haube langgezogen + Doppel-Kupplungsmaul + Wartungsklappe','Kampfraum vom Fahrerhaus entkoppelt + Tritt nach oben abstehend an Heckrampentür'],
    s:'LKW-HAUBE + ENTKOPPELTER KAMPFRAUM' },
  { id:306, nr:306, name:'BTR-60PB',           flag:'🇷🇺', nation:'Russland', images:[],
    m:['Winkelspiegel als Krone über den Frontfenstern + langer Bug mit Schwallbrett','Abgas steil schräg nach unten rechts + Hydrojet mit 2 Hecktüren'],
    s:'WINKELSPIEGEL-KRONE ÜBER FRONTFENSTERN' },
  { id:307, nr:307, name:'BTR-70',             flag:'🇷🇺', nation:'Russland', images:[],
    m:['Einstieg/Absitzen zwischen 2. und 3. Achse (Schießluke über Einstiegstür)','Tropfenförmiger Hydrojet mittig am Heck + grade flache Front'],
    s:'EINSTIEG ZWISCHEN ACHSE 2+3 + TROPFEN-HYDROJET' },
  { id:308, nr:308, name:'BTR-80',             flag:'🇷🇺', nation:'Russland', images:[],
    m:['Tür 2-geteilt + Schießluke mit runder Kappe links + Beifahrer-Schießluke mit runder Blende','Abgasrohr liegende Zigarrenform + Prallbleche + Schutzbügel hinter Turmdrehkranz'],
    s:'GETEILTE TÜR + RUNDE SCHIESSLUKE-KAPPE' },
  { id:309, nr:309, name:'BTR-80A',            flag:'🇷🇺', nation:'Russland', images:[],
    m:['Scheitellafette mit rundem Scheinwerfer + schaufelförmiger Zusatzpanzer am Turm','3 Schießluken rechts + keine Halterung über Abgasrohr am Heck'],
    s:'SCHEITELLAFETTE + SCHAUFELFÖRMIGER ZUSATZPANZER' },
  { id:310, nr:310, name:'BTR-82A',            flag:'🇷🇺', nation:'Russland', images:[],
    m:['Laserkasten auf der BMK (Bordmaschinenkanone) + Panzerung unterhalb der BMK','Schnorchel-Aufnahme am Heck sichtbar'],
    s:'LASERKASTEN AUF BMK + SCHNORCHEL-AUFNAHME HECK' },
  { id:311, nr:311, name:'BTR-MDM',            flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kastenförmiger Aufbau (Kettenfahrzeug!) + 5 Laufrollen + kein klassischer Turm','2× Doppel-Nebelwurfbecher + 1 Blenden-MG vorne + kleines Schwallbrett'],
    s:'KASTENFÖRMIG + 5 LAUFROLLEN (KETTE) + 2× NEBELWURF' },
  { id:312, nr:312, name:'BTR-3',              flag:'🇺🇦', nation:'Ukraine', images:[],
    m:['Ukrainischer Radschützenpanzer auf BTR-80-Basis','Handout-Merkmale eintragen'],
    s:'UKRAINE – HANDOUT AUSSTEHEND' },
  { id:313, nr:313, name:'BTR-4',              flag:'🇺🇦', nation:'Ukraine', images:[],
    m:['Ukrainischer Radschützenpanzer – moderne Variante','Handout-Merkmale eintragen'],
    s:'UKRAINE – HANDOUT AUSSTEHEND' },
  { id:314, nr:314, name:'BTR-D',              flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kleiner flacher Buckel ohne Waffe (kein echter Turm) + Handlauf entlang dem Buckel','2 Blenden-MG vorne in der Wanne + 6 Laufrollen (+1 mehr als BMD-1)'],
    s:'FLACHER BUCKEL OHNE WAFFE + 2 BLENDEN-MG VORNE' },
  { id:315, nr:315, name:'MT-LB',              flag:'🇷🇺', nation:'Russland', images:[],
    m:['Flache langgezogene Wannenfront mit Klappe + Fenster weit auseinander','6 große Laufrollen OHNE Stützrollen + kleiner Ein-Mann-Turm weit vorne (Beifahrerhöhe!)'],
    s:'6 GROSSE LAUFROLLEN OHNE STÜTZE + EIN-MANN-TURM VORNE' },
  { id:316, nr:316, name:'MT-LB VMK',          flag:'🇷🇺', nation:'Russland', images:[],
    m:['Wie MT-LB – identische Wanne und Laufrollen','Kanone vorne auf dem Turm (statt nur MG wie bei MT-LB)'],
    s:'WIE MT-LB + KANONE AUF VORDEREM TURM' },
  { id:317, nr:317, name:'MT-LBu',             flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kompletter oberer Wannenteil sargförmig aufgesetzt (markant größer als MT-LB)','Großer Abstand zwischen Laufrollen und Wannenkörper'],
    s:'SARGFÖRMIGER AUFBAU OBEN + GROSSER ROLLEN-ABSTAND' },
],

aufkl: [
  { id:400, nr:400, name:'BRDM-2',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Bootsförmige Wanne + Stützräder absenkbar','Luke für Hydrojet am Heck (groß) + Seite glatt mit Winkelspiegeln','Zwei Aufstiegshilfen an der Seite'],
    s:'BOOTSFÖRMIG + HYDROJET-LUKE + STÜTZRÄDER' },
  { id:401, nr:401, name:'BRDM-2M',    flag:'🇷🇺', nation:'Russland', images:[],
    m:['Wie BRDM-2 aber mit Tür zusätzlich bekommen','Stützräder entfernt (Unterschied zu BRDM-2)'],
    s:'WIE BRDM-2 + TÜR + KEINE STÜTZRÄDER' },
  { id:402, nr:402, name:'CAYMAN',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Große Scheibe mit Monobogen + 2 Seitenfenster für MKF','Aufgesetzter Staukasten am Heck + Propellerantrieb','Ergonomische Tür mit Fenster + Aufstiegshilfe'],
    s:'MONOBOGEN-SCHEIBE + PROPELLER + ECKIGE RADKÄSTEN' },
  { id:403, nr:403, name:'BPM-97',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Gepanzertes Fahrzeug mit charakteristischem Aufbau'],
    s:'BPM-97 – HANDOUT AUSSTEHEND' },
  { id:404, nr:404, name:'BRM-1',      flag:'🇷🇺', nation:'Russland', images:[],
    m:['Funkmast anliegend – sieht aus wie dünner Schnorchel','Luke auf Wanne nach außen aufklappend','Beule am Turmheck: Luke für Radar'],
    s:'FUNKMAST WIE SCHNORCHEL + RADAR-BEULE AM TURM' },
  { id:405, nr:405, name:'BRM-1K',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Mast über Heck sieht aus wie dünner Schnorchel','Staukästen für Antenne verdecken Schießluken','Winkelspiegel: 1 links – 2 rechts'],
    s:'MASTSCHNORCHEL + ANTENNENSTAUKÄSTEN' },
  { id:406, nr:406, name:'BRM-3K',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kleine Luke und 2 Hydrojets unten','Staukästen an der Seite über dem ersten Rad','BMP-3-Wanne + ein Antennenfuß mittig auf Wanne'],
    s:'BMP-3-WANNE + 2 HYDROJETS + ANTENNENFUSS' },
],

art: [
  { id:500, nr:500, name:'2A36',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Teller unterhalb Kanone erkennbar + Schild links und rechts neben Verschluss','3 aufliegende Rohrrückholer mit Dach + Mündungsbremse 5 Kammern schmal','4 Räder + Spreizlafette'],
    s:'TELLER UNTER KANONE + 5-KAMMER-MÜNDUNG + 3 RÜCKHOLER MIT DACH' },
  { id:501, nr:501, name:'2A65',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Ein Stützteller + kleiner Schild + Staukästen hinter Schild','2 Rohrrückholer OHNE Dach + kleines Gitter über Verschluss','3 große Kammern Mündungsbremse + 2 Räder + lange Spreizlafette'],
    s:'KEIN DACH RÜCKHOLER + 3-KAMMER-MÜNDUNG + 2 RÄDER' },
  { id:502, nr:502, name:'D-1',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Schutzschild mit verschiebbarem Mittelteil + Staukasten an Schild außen','Verschluss würfelförmig + kurzes Rohr'],
    s:'VERSCHIEBBARES SCHILD + WÜRFELVERSCHLUSS + KURZES ROHR' },
  { id:503, nr:503, name:'D-20',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Wellige Schildoberkante abklappbar + Reifen leicht schräg in Schussposition','Stützteller unter Kanone + Rückholer schauen knapp vor dem Schild raus'],
    s:'WELLIGE SCHILDKANTE + SCHRÄGE REIFEN + STÜTZTELLER' },
  { id:504, nr:504, name:'D-30',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Zugöse an Mündungsbremse + kleines Schild','Rückholer in einem Kasten auf dem Rohr + 6 Kammern'],
    s:'ZUGÖSE AN MÜNDUNG + RÜCKHOLER IM KASTEN' },
  { id:520, nr:520, name:'2S1',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Motor vorne + MKF rechts mit einer Luke + nur eine Luke mit Schussblende','Eine Optik links vom Rohr'],
    s:'MOTOR VORNE + MKF RECHTS + SCHUSSBLENDE' },
  { id:521, nr:521, name:'2S3',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Räum-/Schiebeschild (entfernbar) + 2 Keile auf der Wanne in Höhe Motor','Turm wirkt fast breiter als Wanne + 3 Halterungen am Turm'],
    s:'RÄUMSCHILD + TURM BREITER ALS WANNE + 3 HALTERUNGEN' },
  { id:522, nr:522, name:'2S5',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Schild für Bediener linke Seite + dreizahniges Gegenlager abklappbar','Abgeschrägte Kanten + offenliegendes Geschütz'],
    s:'BEDIENERSCHILD LINKS + DREIZAHN-GEGENLAGER + OFFEN' },
  { id:523, nr:523, name:'2S7',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Fahrerhaus kantig mit 2 Anschlagpunkten + große Schaufel','Große Hydraulikzylinder + Käfige und keine Schilder'],
    s:'KANTIG FAHRERHAUS + GROSSE SCHAUFEL + HYDRAULIK' },
  { id:524, nr:524, name:'2S9',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['2 Winkelspiegel nach hinten am Turm + kurzes dickes Rohr','Fällt schräg ab + Walzenblende'],
    s:'KURZES DICKES ROHR + WALZENBLENDE + SCHRÄG' },
  { id:525, nr:525, name:'2S19',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Turm doppelt so groß wie Wanne + Ladearm nach oben hochgeklappt mittig','Abluftkanal links und rechts vom Turm'],
    s:'RIESIGER TURM + LADEARM OBEN + ABLUFTKANÄLE' },
  { id:526, nr:526, name:'2S23',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kellerschacht am Turm links + Kugel mit Optik links am Turm','BTR-70-Wanne + Auspuff vom BTR-80'],
    s:'BTR-70-WANNE + KELLERSCHACHT + KUGELOPTIK' },
  { id:527, nr:527, name:'2S31',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Kurzes Schwallbrett + Blenden-MG in extra Rohr rechts neben Rohr','Ladeluke links nach unten aufklappbar + Ladeschiene am Turm'],
    s:'SCHWALLBRETT + MG NEBEN ROHR + LADELUKE LINKS' },
  { id:528, nr:528, name:'2S34',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Über Wannenkante rausragend + fliegenförmig','MTLB-Wanne'],
    s:'FLIEGENFORM + MTLB-WANNE + RAGT ÜBER KANTE' },
  { id:529, nr:529, name:'2S43',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Fahrerhaus mit zwei Türen links und rechts + Nebelmittel auf dem Dach','2 tellerförmige Bodenplatten + großer Kasten neben dem Rohr'],
    s:'2 TÜREN FAHRERHAUS + TELLERPLATTEN + KASTEN AM ROHR' },
  { id:530, nr:530, name:'2B11',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Lafette abklappbar + Bodenplatte mit 4 Griffen + Krone zur Sicherung'],
    s:'ABKLAPPBARE LAFETTE + 4-GRIFF-PLATTE + KRONE' },
  { id:531, nr:531, name:'2S4',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Große viereckige Bodenplatte mit Sonnenmuster + liegt schräg auf dem Rohr','Kran zum Beladen + reicht bis 2/3 der Fahrzeuglänge'],
    s:'SONNENMUSTER-BODENPLATTE + KRAN + 2/3 LÄNGE' },
  { id:532, nr:532, name:'2B23',  flag:'🇷🇺', nation:'Russland', images:[],
    m:['Zurhaken am Rohr + Doppel-T-Haltegriff am Ende des Rohres','Räder an der Lafette selbst angebracht + werden hochgeklappt'],
    s:'DOPPEL-T-GRIFF + HOCHKLAPPBARE LAFETTENRÄDER' },
  { id:533, nr:533, name:'2B9',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Mit Magazin geladen + 3 Rohrrückholer (einer oben, 2 drauf)','Lafettenstangen mit kleinen Keilen am Ende'],
    s:'MAGAZINGELADEN + 3 RÜCKHOLER + KEILE AN LAFETTE' },
],

mlrs: [
  { id:600, nr:600, name:'BM-21 GRAD',     flag:'🇷🇺', nation:'Russland', images:[],
    m:['Raketenpaket immer schräg mit 40 gleichmäßigen Rohren + 4 Startreihen','Ummantelung um das Paket + Auslösung vom Beifahrer','Halterung für Optik hinten links am Werferpaket'],
    s:'40 ROHRE SCHRÄG + 4 REIHEN + UMMANTELUNG' },
  { id:601, nr:601, name:'BM-27 URAGAN',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Achse 1-2-1 + Fahrerhaus mit Nase + Frontscheibe mit Schutzklappe nach unten abklappbar','Startbehälter in Fahrtrichtung gedreht + großer Kühler hinter Fahrerhaus','2 Stützen am Heck + 4 Raketen oben aufliegend versetzt'],
    s:'ACHSE 1-2-1 + NASE FAHRERHAUS + KÜHLER HINTER HAUS' },
  { id:602, nr:602, name:'BM-30 SMERCH',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['Breiter Kühler mit Doppelkabine (MKF + Beifahrer hintereinander)','Schießkabine hinter Fahrerhaus + 3× 4er Bündel + 4-Achsen-Fahrzeug','Stützen zwischen Achse 3 und 4'],
    s:'DOPPELKABINE + 3×4 BÜNDEL + 4 ACHSEN' },
  { id:604, nr:604, name:'TOS-1 BURATINO', flag:'🇷🇺', nation:'Russland', images:[],
    m:['4 Abschussreihen + oberste Reihe mit weniger Raketen','Auf Panzer-Wanne (T-72-Basis)'],
    s:'4 REIHEN + OBEN WENIGER RAKETEN + PANZERWANNE' },
  { id:605, nr:605, name:'TOS-1A',         flag:'🇷🇺', nation:'Russland', images:[],
    m:['Gleichmäßiges Werferpaket mit 3 Reihen + Stützbeine am Heck','Nachladefzg mit Kran in der Mitte und gleichmäßigem Paket'],
    s:'3 GLEICHMÄSS. REIHEN + STÜTZBEINE HECK' },
  { id:606, nr:606, name:'TOS-2 TOSOCHKA', flag:'🇷🇺', nation:'Russland', images:[],
    m:['Links einen Kranarm an Kasten + Trittbleche werden aufgeklappt','Heckklappe schaufelförmig + Stützbeine hinter letzter Achse'],
    s:'KRANARM LINKS + SCHAUFEL-HECK + AUFKLAPPBAR' },
  { id:607, nr:607, name:'9A54 TORNADO',   flag:'🇷🇺', nation:'Russland', images:[],
    m:['6 Raketen auf 4-Achsen-LKW + umlaufende Windungen am Rohr','2 Stützen am Heck'],
    s:'6 RAKETEN + 4 ACHSEN + WINDUNGEN AM ROHR' },
],
}

export function getFilteredVehicles(catKey, superCat) {
  const cat = CATS[catKey]
  if (!cat) return []
  const sc = SUPER_CATS[superCat]
  if (!sc || sc.nations.length === 0) return []
  return DB[catKey].filter(v => sc.nations.includes(v.nation))
}

export function getRecomonkeyUrl(vehicle, catKey) {
  const type = CATS[catKey]?.recoType || 'Vehicles'
  const name = encodeURIComponent(vehicle.name)
  return `https://www.recomonkey.com/Land-Platforms/${type}/${name}`
}
